#!/bin/bash

set -x

main() {
  stack_name=${1:?must provide CloudFormation stack name}

  # Delete all the objects in the S3 bucket so that the stack delete will succeed.
  bucket=$(aws cloudformation describe-stack-resources --stack-name "${stack_name}" --logical-resource-id S3Bucket --query StackResources[0].PhysicalResourceId --output text)
  aws s3 rm s3://"${bucket}"/ --recursive

  aws cloudformation delete-stack --stack-name="${stack_name}-lambda"
  aws cloudformation wait stack-delete-complete --stack-name="${stack_name}-lambda"

  aws cloudformation delete-stack --stack-name="${stack_name}"
  aws cloudformation wait stack-delete-complete --stack-name="${stack_name}"
}

main "$@"
