# S3 bucket for the datasette stack
AWSTemplateFormatVersion: 2010-09-09
Description: Bucket for SQLite database and Datasette stub code.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
